# this is used by repo2docker to get python (and crucially) non-python things
# like nodejs.
# on mybinder.org's default container, it will be installed into the local
# conda `root` environment, located in `/opt/conda`

name: keras-ipywebrtc

channels:
  - conda-forge
  - defaults

dependencies:
  - ipywidgets >=7.5.0,<8
  - nodejs >=8.9.3
  - notebook >=5.3.0,<6
  - pip
  - python >=3.6,<3.7
  - setuptools
  - pillow
  - scikit-image
  - pythreejs
  - ipyleaflet
  - tensorflow
  - keras
  - pip:
    - git+https://github.com/maartenbreddels/ipywebrtc
